apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata: 
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: 602917784174.dkr.ecr.us-east-2.amazonaws.com/wisecow:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4499

        

