name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to Container Registry
        # run: |

        #   docker build -t app .
        #   docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        #   docker tag app aniketdubey/test
        #   docker push aniketdubey/test

    

      # docker tag local-image:tagname new-repo:tagname
      # docker push new-repo:tagname


      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
      
          docker build -t aniketdubey/test:latest .
          docker push aniketdubey/test:latest


        